# Đặt tên
name: CI docker

# Khi nào chạy
on:
  push:
    branches: ["master"]

# chạy công việc gì
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Đăng nhập vào docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build image
        run: docker build . -t toanphangl1997/img-be_cyber_media:latest

      - name: push image lên docker hub
        run: docker push toanphangl1997/img-be_cyber_media:latest
